/* Generated from backend/src/common/utils/stops.ts by scripts/sync-web-libs.mjs (source sha256 57ee39702ed0ff87).
   Do not edit: change the source, run the script, and commit both. */
(function (root) {
  var module = { exports: {} };
  var exports = module.exports;
  "use strict";
  /**
   * The stops along a bus's road, in travel order: the road guide's stops for the direction
   * the bus is going, joined with the businesses that list themselves on this corridor.
   * Shared with the reader (web/js/lib/stops.js, generated by scripts/sync-web-libs.mjs),
   * so it has no imports and one test suite covers both.
   */
  Object.defineProperty(exports, "__esModule", { value: true });
  exports.directionsUrl = exports.kathmanduMinutes = exports.kindInfo = exports.FILTERS = void 0;
  exports.openState = openState;
  exports.buildTimeline = buildTimeline;
  exports.whatsappUrl = whatsappUrl;
  exports.FILTERS = [
      ['food', 'Food'], ['rest', 'Rest & toilets'], ['fuel', 'Fuel'], ['atm', 'ATM'],
      ['stay', 'Stay'], ['do', 'Things to do'], ['view', 'Viewpoints'],
  ];
  /** Road guide stop kinds and business categories, to one filter, an icon and a label. */
  const KINDS = {
      FOOD: ['food', '🍛', 'Food'], RESTAURANT: ['food', '🍛', 'Restaurant'], CAFE: ['food', '☕', 'Café'],
      REST_STOP: ['rest', '🚻', 'Rest stop'], FUEL: ['fuel', '⛽', 'Fuel'], ATM: ['atm', '🏧', 'ATM'],
      HOTEL: ['stay', '🏨', 'Hotel'], HOMESTAY: ['stay', '🏡', 'Homestay'], LODGE: ['stay', '🛏', 'Lodge'],
      ACTIVITY: ['do', '🧗', 'Activity'], LANDMARK: ['do', '🏛', 'Landmark'], TEMPLE: ['do', '🛕', 'Temple'],
      SHOPPING: ['do', '🛍', 'Shopping'], ADVENTURE: ['do', '🧗', 'Adventure'], PARAGLIDING: ['do', '🪂', 'Paragliding'],
      TREKKING_AGENCY: ['do', '🥾', 'Trekking agency'], TOUR_OPERATOR: ['do', '🚐', 'Tours'], HANDICRAFT: ['do', '🧶', 'Handicrafts'],
      GUIDE: ['do', '🧭', 'Guide'], RENTAL: ['do', '🛵', 'Rentals'],
      VIEWPOINT: ['view', '🌄', 'Viewpoint'], HOSPITAL: ['health', '🏥', 'Hospital'], OTHER: ['other', '📍', 'Stop'],
  };
  const kindInfo = (kind) => { var _a; return (_a = KINDS[kind]) !== null && _a !== void 0 ? _a : KINDS.OTHER; };
  exports.kindInfo = kindInfo;
  const DEV = '०१२३४५६७८९';
  /** Minutes past midnight in Kathmandu (UTC+05:45, no daylight saving). */
  const kathmanduMinutes = (at) => Math.floor((at.getTime() / 60000 + 345) % 1440 + 1440) % 1440;
  exports.kathmanduMinutes = kathmanduMinutes;
  function clock(m) {
      const h = Math.floor(m / 60) % 24;
      const min = m % 60;
      const h12 = h % 12 || 12;
      return `${h12}${min ? `:${String(min).padStart(2, '0')}` : ''}${h < 12 ? 'am' : 'pm'}`;
  }
  /**
   * Whether a stop is open now, from opening hours as an editor wrote them: "6am–9pm",
   * "06:00-21:00", "7 am to 10 pm daily", "24 hours", "6–10am, 4–9pm", "6pm–2am". Anything
   * it cannot read is "unknown", never a guess.
   */
  function openState(text, at) {
      const raw = (text !== null && text !== void 0 ? text : '').toLowerCase().replace(/[०-९]/g, (d) => String(DEV.indexOf(d))).trim();
      if (!raw)
          return { state: 'unknown', label: '' };
      if (/24\s*(hours|hrs|h)\b|24\s*\/\s*7|always open|open all day/.test(raw))
          return { state: 'open', label: 'Open 24 hours' };
      const time = String.raw `(\d{1,2})(?:[:.](\d{2}))?\s*(am|pm|a\.m\.|p\.m\.)?`;
      const re = new RegExp(`${time}\\s*(?:-|–|—|to)\\s*${time}`, 'g');
      const ranges = [];
      for (const m of raw.matchAll(re)) {
          const toMin = (h, mm, mer) => {
              let hour = Number(h);
              if (hour > 24 || Number(mm !== null && mm !== void 0 ? mm : 0) > 59)
                  return null;
              if ((mer === null || mer === void 0 ? void 0 : mer.startsWith('p')) && hour < 12)
                  hour += 12;
              if ((mer === null || mer === void 0 ? void 0 : mer.startsWith('a')) && hour === 12)
                  hour = 0;
              return (hour % 24) * 60 + Number(mm !== null && mm !== void 0 ? mm : 0);
          };
          let endMer = m[6];
          let startMer = m[3];
          // "6–9pm" means 6pm; "10–6pm" means 10am. The start takes the end's half of the day unless that puts it after the end.
          if (!startMer && endMer) {
              const asPm = toMin(m[1], m[2], endMer);
              const end = toMin(m[4], m[5], endMer);
              startMer = asPm != null && end != null && asPm < end ? endMer : 'am';
          }
          if (!endMer && startMer && !m[5] && Number(m[4]) <= 12 && Number(m[4]) < Number(m[1]))
              endMer = 'pm';
          const start = toMin(m[1], m[2], startMer);
          const end = toMin(m[4], m[5], endMer);
          if (start != null && end != null && start !== end)
              ranges.push([start, end]);
      }
      if (!ranges.length)
          return { state: 'unknown', label: '' };
      const now = (0, exports.kathmanduMinutes)(at);
      for (const [start, end] of ranges) {
          const inside = start < end ? now >= start && now < end : now >= start || now < end;
          if (inside)
              return { state: 'open', label: `Open now · until ${clock(end)}` };
      }
      // The next opening today or tomorrow.
      const next = ranges.map(([start]) => ((start - now + 1440) % 1440)).reduce((a, b) => Math.min(a, b));
      return { state: 'closed', label: `Closed · opens ${clock((now + next) % 1440)}` };
  }
  /** Districts of the places buses usually end at, so a Kaski hotel counts as "at Pokhara". */
  const DISTRICT_OF = {
      pokhara: 'kaski', kathmandu: 'kathmandu', chitwan: 'chitwan', sauraha: 'chitwan', bharatpur: 'chitwan',
      lumbini: 'rupandehi', butwal: 'rupandehi', bhairahawa: 'rupandehi', biratnagar: 'morang', janakpur: 'dhanusha',
      dharan: 'sunsari', nepalgunj: 'banke', dhangadhi: 'kailali', besisahar: 'lamjung', jomsom: 'mustang',
  };
  /**
   * Groups the stops for this direction: "Coming up" (the next three), "Later on the road",
   * "At <destination>", and businesses on the corridor with no place on the road guide.
   * Where the bus is comes from minutes since it left (the crew's trip, or the scan); with
   * neither, everything is ahead. Stops already passed are counted, not shown.
   */
  function buildTimeline(input) {
      var _a;
      const { stops, businesses, route, direction, minutesElapsed, now, filter } = input;
      const destination = direction === 'REVERSE' ? route.startPlace : route.endPlace;
      const distance = (_a = route.distanceKm) !== null && _a !== void 0 ? _a : null;
      // Minutes per km when a stop has a distance but no time.
      const pace = distance && route.typicalHours ? (route.typicalHours * 60) / distance : 2;
      const byId = new Map(businesses.map((b) => [b.id, b]));
      const placed = new Set();
      const fromBusiness = (b) => {
          var _a, _b, _c, _d, _e;
          return ({
              verified: !!b.verifiedAt,
              // Listing on a corridor is paid; the reader labels it.
              paid: true,
              phone: (_a = b.phone) !== null && _a !== void 0 ? _a : null, whatsapp: (_b = b.whatsapp) !== null && _b !== void 0 ? _b : null, slug: b.slug,
              price: (_c = b.priceRange) !== null && _c !== void 0 ? _c : null, lat: (_d = b.latitude) !== null && _d !== void 0 ? _d : null, lng: (_e = b.longitude) !== null && _e !== void 0 ? _e : null,
          });
      };
      const guide = stops.map((s) => {
          var _a, _b, _c, _d, _e, _f, _g, _h;
          const [f, icon, type] = (0, exports.kindInfo)(s.kind);
          const biz = s.businessId ? byId.get(s.businessId) : undefined;
          if (biz)
              placed.add(biz.id);
          const minutes = (_a = s.minutesFromStart) !== null && _a !== void 0 ? _a : (s.distanceFromStartKm != null ? Math.round(s.distanceFromStartKm * pace) : null);
          const stop = {
              key: `stop:${s.id}`, name: s.name, filter: f, icon, type,
              km: (_b = s.distanceFromStartKm) !== null && _b !== void 0 ? _b : null, minutesFromStart: minutes,
              inMinutes: minutes != null && minutesElapsed != null ? minutes - minutesElapsed : null,
              price: s.priceFromNpr ? `from NPR ${s.priceFromNpr.toLocaleString('en-IN')}` : null,
              hours: openState(s.openingHours, now), verified: false, paid: false, highlight: !!s.isHighlight,
              phone: (_c = s.contactPhone) !== null && _c !== void 0 ? _c : null, whatsapp: null, lat: (_d = s.latitude) !== null && _d !== void 0 ? _d : null, lng: (_e = s.longitude) !== null && _e !== void 0 ? _e : null,
              slug: null, description: (_f = s.description) !== null && _f !== void 0 ? _f : null,
          };
          // The business's own name: it is who the Call button reaches.
          return biz ? { ...stop, ...fromBusiness(biz), name: biz.name, phone: (_g = biz.phone) !== null && _g !== void 0 ? _g : stop.phone, price: (_h = biz.priceRange) !== null && _h !== void 0 ? _h : stop.price } : stop;
      });
      const listed = businesses.filter((b) => !placed.has(b.id)).map((b) => {
          const [f, icon, type] = (0, exports.kindInfo)(b.category);
          return {
              key: `biz:${b.id}`, name: b.name, filter: f, icon, type, km: null, minutesFromStart: null, inMinutes: null,
              hours: { state: 'unknown', label: '' }, highlight: false, description: null,
              ...fromBusiness(b),
          };
      });
      const keep = (s) => !filter || s.filter === filter;
      const atEnd = (s) => s.km != null && distance != null && s.km >= distance - 3;
      const destKey = destination.toLowerCase();
      const inDestination = (b) => {
          var _a;
          const district = ((_a = b === null || b === void 0 ? void 0 : b.district) !== null && _a !== void 0 ? _a : '').toLowerCase();
          return !!district && (district.includes(destKey) || district === DISTRICT_OF[destKey]);
      };
      const ahead = [];
      let passed = 0;
      const atDestination = [];
      for (const s of guide.sort((a, b) => { var _a, _b, _c, _d; return ((_b = (_a = a.minutesFromStart) !== null && _a !== void 0 ? _a : a.km) !== null && _b !== void 0 ? _b : 0) - ((_d = (_c = b.minutesFromStart) !== null && _c !== void 0 ? _c : b.km) !== null && _d !== void 0 ? _d : 0); })) {
          if (!keep(s))
              continue;
          if (atEnd(s)) {
              atDestination.push(s);
              continue;
          }
          if (s.inMinutes != null && s.inMinutes < -5) {
              passed += 1;
              continue;
          }
          ahead.push(s);
      }
      const alongTheRoad = [];
      for (const s of listed) {
          if (!keep(s))
              continue;
          (inDestination(byId.get(s.key.slice(4))) ? atDestination : alongTheRoad).push(s);
      }
      return {
          destination,
          comingUp: ahead.slice(0, 3),
          later: ahead.slice(3),
          atDestination,
          alongTheRoad,
          passed,
          total: ahead.length + atDestination.length + alongTheRoad.length,
      };
  }
  /** Directions to a stop, in whatever maps app the phone has. */
  const directionsUrl = (s) => s.lat != null && s.lng != null ? `https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lng}` : null;
  exports.directionsUrl = directionsUrl;
  /** WhatsApp's own link for a Nepali mobile number written any way. */
  function whatsappUrl(number) {
      const digits = String(number !== null && number !== void 0 ? number : '').replace(/\D/g, '');
      if (digits.length < 8)
          return null;
      return `https://wa.me/${digits.length === 10 && digits.startsWith('9') ? `977${digits}` : digits}`;
  }
  
  root.Stops = module.exports;
})(typeof self !== 'undefined' ? self : this);
