/**
 * The stops along a bus's road, in travel order: the road guide's stops for the direction
 * the bus is going, joined with the businesses that list themselves on this corridor.
 * Shared with the reader (web/js/lib/stops.js, generated by scripts/sync-web-libs.mjs),
 * so it has no imports and one test suite covers both.
 */

export type StopFilter = 'food' | 'rest' | 'fuel' | 'atm' | 'stay' | 'do' | 'view' | 'health' | 'other';

export const FILTERS: Array<[StopFilter, string]> = [
  ['food', 'Food'], ['rest', 'Rest & toilets'], ['fuel', 'Fuel'], ['atm', 'ATM'],
  ['stay', 'Stay'], ['do', 'Things to do'], ['view', 'Viewpoints'],
];

/** Road guide stop kinds and business categories, to one filter, an icon and a label. */
const KINDS: Record<string, [StopFilter, string, string]> = {
  FOOD: ['food', '🍛', 'Food'], RESTAURANT: ['food', '🍛', 'Restaurant'], CAFE: ['food', '☕', 'Café'],
  REST_STOP: ['rest', '🚻', 'Rest stop'], FUEL: ['fuel', '⛽', 'Fuel'], ATM: ['atm', '🏧', 'ATM'],
  HOTEL: ['stay', '🏨', 'Hotel'], HOMESTAY: ['stay', '🏡', 'Homestay'], LODGE: ['stay', '🛏', 'Lodge'],
  ACTIVITY: ['do', '🧗', 'Activity'], LANDMARK: ['do', '🏛', 'Landmark'], TEMPLE: ['do', '🛕', 'Temple'],
  SHOPPING: ['do', '🛍', 'Shopping'], ADVENTURE: ['do', '🧗', 'Adventure'], PARAGLIDING: ['do', '🪂', 'Paragliding'],
  TREKKING_AGENCY: ['do', '🥾', 'Trekking agency'], TOUR_OPERATOR: ['do', '🚐', 'Tours'], HANDICRAFT: ['do', '🧶', 'Handicrafts'],
  GUIDE: ['do', '🧭', 'Guide'], RENTAL: ['do', '🛵', 'Rentals'],
  VIEWPOINT: ['view', '🌄', 'Viewpoint'], HOSPITAL: ['health', '🏥', 'Hospital'], OTHER: ['other', '📍', 'Stop'],
};
export const kindInfo = (kind: string) => KINDS[kind] ?? KINDS.OTHER;

// ---------------------------------------------------------------- opening hours

export interface OpenState { state: 'open' | 'closed' | 'unknown'; label: string }

const DEV = '०१२३४५६७८९';
/** Minutes past midnight in Kathmandu (UTC+05:45, no daylight saving). */
export const kathmanduMinutes = (at: Date) => Math.floor((at.getTime() / 60000 + 345) % 1440 + 1440) % 1440;

function clock(m: number): string {
  const h = Math.floor(m / 60) % 24;
  const min = m % 60;
  const h12 = h % 12 || 12;
  return `${h12}${min ? `:${String(min).padStart(2, '0')}` : ''}${h < 12 ? 'am' : 'pm'}`;
}

/**
 * Whether a stop is open now, from opening hours as an editor wrote them: "6am–9pm",
 * "06:00-21:00", "7 am to 10 pm daily", "24 hours", "6–10am, 4–9pm", "6pm–2am". Anything
 * it cannot read is "unknown", never a guess.
 */
export function openState(text: string | null | undefined, at: Date): OpenState {
  const raw = (text ?? '').toLowerCase().replace(/[०-९]/g, (d) => String(DEV.indexOf(d))).trim();
  if (!raw) return { state: 'unknown', label: '' };
  if (/24\s*(hours|hrs|h)\b|24\s*\/\s*7|always open|open all day/.test(raw)) return { state: 'open', label: 'Open 24 hours' };
  const time = String.raw`(\d{1,2})(?:[:.](\d{2}))?\s*(am|pm|a\.m\.|p\.m\.)?`;
  const re = new RegExp(`${time}\\s*(?:-|–|—|to)\\s*${time}`, 'g');
  const ranges: Array<[number, number]> = [];
  for (const m of raw.matchAll(re)) {
    const toMin = (h: string, mm: string | undefined, mer: string | undefined) => {
      let hour = Number(h);
      if (hour > 24 || Number(mm ?? 0) > 59) return null;
      if (mer?.startsWith('p') && hour < 12) hour += 12;
      if (mer?.startsWith('a') && hour === 12) hour = 0;
      return (hour % 24) * 60 + Number(mm ?? 0);
    };
    let endMer = m[6];
    let startMer = m[3];
    // "6–9pm" means 6pm; "10–6pm" means 10am. The start takes the end's half of the day unless that puts it after the end.
    if (!startMer && endMer) {
      const asPm = toMin(m[1], m[2], endMer);
      const end = toMin(m[4], m[5], endMer);
      startMer = asPm != null && end != null && asPm < end ? endMer : 'am';
    }
    if (!endMer && startMer && !m[5] && Number(m[4]) <= 12 && Number(m[4]) < Number(m[1])) endMer = 'pm';
    const start = toMin(m[1], m[2], startMer);
    const end = toMin(m[4], m[5], endMer);
    if (start != null && end != null && start !== end) ranges.push([start, end]);
  }
  if (!ranges.length) return { state: 'unknown', label: '' };
  const now = kathmanduMinutes(at);
  for (const [start, end] of ranges) {
    const inside = start < end ? now >= start && now < end : now >= start || now < end;
    if (inside) return { state: 'open', label: `Open now · until ${clock(end)}` };
  }
  // The next opening today or tomorrow.
  const next = ranges.map(([start]) => ((start - now + 1440) % 1440)).reduce((a, b) => Math.min(a, b));
  return { state: 'closed', label: `Closed · opens ${clock((now + next) % 1440)}` };
}

// ---------------------------------------------------------------- the timeline

export interface GuideStopIn {
  id: string; kind: string; name: string; description?: string | null;
  distanceFromStartKm?: number | null; minutesFromStart?: number | null;
  priceFromNpr?: number | null; openingHours?: string | null; contactPhone?: string | null;
  businessId?: string | null; latitude?: number | null; longitude?: number | null; isHighlight?: boolean;
}
export interface BusinessIn {
  id: string; slug: string; name: string; category: string; tier?: string; priceRange?: string | null;
  district?: string | null; latitude?: number | null; longitude?: number | null; verifiedAt?: string | Date | null;
  phone?: string | null; whatsapp?: string | null;
}
export interface RouteIn { startPlace: string; endPlace: string; distanceKm?: number | null; typicalHours?: number | null }

export interface Stop {
  key: string; name: string; filter: StopFilter; icon: string; type: string;
  km: number | null; minutesFromStart: number | null; inMinutes: number | null;
  price: string | null; hours: OpenState; verified: boolean; paid: boolean; highlight: boolean;
  phone: string | null; whatsapp: string | null; lat: number | null; lng: number | null;
  slug: string | null; description: string | null;
}

/** Districts of the places buses usually end at, so a Kaski hotel counts as "at Pokhara". */
const DISTRICT_OF: Record<string, string> = {
  pokhara: 'kaski', kathmandu: 'kathmandu', chitwan: 'chitwan', sauraha: 'chitwan', bharatpur: 'chitwan',
  lumbini: 'rupandehi', butwal: 'rupandehi', bhairahawa: 'rupandehi', biratnagar: 'morang', janakpur: 'dhanusha',
  dharan: 'sunsari', nepalgunj: 'banke', dhangadhi: 'kailali', besisahar: 'lamjung', jomsom: 'mustang',
};

export interface Timeline {
  destination: string;
  comingUp: Stop[]; later: Stop[]; atDestination: Stop[]; alongTheRoad: Stop[];
  passed: number; total: number;
}

/**
 * Groups the stops for this direction: "Coming up" (the next three), "Later on the road",
 * "At <destination>", and businesses on the corridor with no place on the road guide.
 * Where the bus is comes from minutes since it left (the crew's trip, or the scan); with
 * neither, everything is ahead. Stops already passed are counted, not shown.
 */
export function buildTimeline(input: {
  stops: GuideStopIn[]; businesses: BusinessIn[]; route: RouteIn; direction: 'FORWARD' | 'REVERSE' | null;
  minutesElapsed: number | null; now: Date; filter?: StopFilter | '';
}): Timeline {
  const { stops, businesses, route, direction, minutesElapsed, now, filter } = input;
  const destination = direction === 'REVERSE' ? route.startPlace : route.endPlace;
  const distance = route.distanceKm ?? null;
  // Minutes per km when a stop has a distance but no time.
  const pace = distance && route.typicalHours ? (route.typicalHours * 60) / distance : 2;
  const byId = new Map(businesses.map((b) => [b.id, b]));
  const placed = new Set<string>();

  const fromBusiness = (b: BusinessIn): Partial<Stop> => ({
    verified: !!b.verifiedAt,
    // Listing on a corridor is paid; the reader labels it.
    paid: true,
    phone: b.phone ?? null, whatsapp: b.whatsapp ?? null, slug: b.slug,
    price: b.priceRange ?? null, lat: b.latitude ?? null, lng: b.longitude ?? null,
  });

  const guide: Stop[] = stops.map((s) => {
    const [f, icon, type] = kindInfo(s.kind);
    const biz = s.businessId ? byId.get(s.businessId) : undefined;
    if (biz) placed.add(biz.id);
    const minutes = s.minutesFromStart ?? (s.distanceFromStartKm != null ? Math.round(s.distanceFromStartKm * pace) : null);
    const stop: Stop = {
      key: `stop:${s.id}`, name: s.name, filter: f, icon, type,
      km: s.distanceFromStartKm ?? null, minutesFromStart: minutes,
      inMinutes: minutes != null && minutesElapsed != null ? minutes - minutesElapsed : null,
      price: s.priceFromNpr ? `from NPR ${s.priceFromNpr.toLocaleString('en-IN')}` : null,
      hours: openState(s.openingHours, now), verified: false, paid: false, highlight: !!s.isHighlight,
      phone: s.contactPhone ?? null, whatsapp: null, lat: s.latitude ?? null, lng: s.longitude ?? null,
      slug: null, description: s.description ?? null,
    };
    // The business's own name: it is who the Call button reaches.
    return biz ? { ...stop, ...fromBusiness(biz), name: biz.name, phone: biz.phone ?? stop.phone, price: biz.priceRange ?? stop.price } : stop;
  });

  const listed: Stop[] = businesses.filter((b) => !placed.has(b.id)).map((b) => {
    const [f, icon, type] = kindInfo(b.category);
    return {
      key: `biz:${b.id}`, name: b.name, filter: f, icon, type, km: null, minutesFromStart: null, inMinutes: null,
      hours: { state: 'unknown', label: '' }, highlight: false, description: null,
      ...fromBusiness(b),
    } as Stop;
  });

  const keep = (s: Stop) => !filter || s.filter === filter;
  const atEnd = (s: Stop) => s.km != null && distance != null && s.km >= distance - 3;
  const destKey = destination.toLowerCase();
  const inDestination = (b?: BusinessIn) => {
    const district = (b?.district ?? '').toLowerCase();
    return !!district && (district.includes(destKey) || district === DISTRICT_OF[destKey]);
  };

  const ahead: Stop[] = [];
  let passed = 0;
  const atDestination: Stop[] = [];
  for (const s of guide.sort((a, b) => (a.minutesFromStart ?? a.km ?? 0) - (b.minutesFromStart ?? b.km ?? 0))) {
    if (!keep(s)) continue;
    if (atEnd(s)) { atDestination.push(s); continue; }
    if (s.inMinutes != null && s.inMinutes < -5) { passed += 1; continue; }
    ahead.push(s);
  }
  const alongTheRoad: Stop[] = [];
  for (const s of listed) {
    if (!keep(s)) continue;
    (inDestination(byId.get(s.key.slice(4))) ? atDestination : alongTheRoad).push(s);
  }
  return {
    destination,
    comingUp: ahead.slice(0, 3),
    later: ahead.slice(3),
    atDestination,
    alongTheRoad,
    passed,
    total: ahead.length + atDestination.length + alongTheRoad.length,
  };
}

/** Directions to a stop, in whatever maps app the phone has. */
export const directionsUrl = (s: Pick<Stop, 'lat' | 'lng' | 'name'>) =>
  s.lat != null && s.lng != null ? `https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lng}` : null;

/** WhatsApp's own link for a Nepali mobile number written any way. */
export function whatsappUrl(number: string | null | undefined): string | null {
  const digits = String(number ?? '').replace(/\D/g, '');
  if (digits.length < 8) return null;
  return `https://wa.me/${digits.length === 10 && digits.startsWith('9') ? `977${digits}` : digits}`;
}
