import { Type } from 'class-transformer';
import { IsBoolean, IsInt, IsOptional, IsString, Min } from 'class-validator';

export class ResolveScanDto {
  /** Anonymous device id generated by the PWA and stored locally. */
  @IsOptional() @IsString() sessionId?: string;
}

export class CreateQrBatchDto {
  @IsString() operatorId: string;
  @IsOptional() @IsString() vehicleId?: string;
  @IsOptional() @IsString() routeId?: string;
  /** Number of stickers to mint — usually the seat count of the bus. */
  @Type(() => Number) @IsInt() @Min(1) count: number;
  @IsOptional() @IsString() placement?: string;
  /** When true, seat numbers 1..count are assigned automatically. */
  @IsOptional() @IsBoolean() numberSeats?: boolean;
}
